//
// Created by JOHANES MATSEBA on 2022/10/26.
//

#ifndef PROJECTASSIGNMENT_WARPARTICIPANTS_H
#define PROJECTASSIGNMENT_WARPARTICIPANTS_H


class WarParticipants {

};


#endif //PROJECTASSIGNMENT_WARPARTICIPANTS_H
